account/urls.py
from django.urls import path
from .views import index,signup,logout_user,profile_image,activate_account


app_name = "account"

urlpatterns = [
    path('', index,name="sign_in"),
    path('signup/', signup,name="sign_up"),
    path('logout',logout_user,name="logout"),
    path('profile_image/',profile_image,name="upload_image"),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate_account, name='activate')
]

cart/urls.py
from django.urls import path 
from .views import (
    cart_home,
    checkout_home,
    cart_update,
    cart_remove,
    cart_update_customer
)


app_name = 'cart'

urlpatterns = [
    path('',cart_home,name= 'cart_home'),
     path('checkout',checkout_home,name= 'checkout'),
     path('update',cart_update,name= 'cart_update'),
     path('remove',cart_remove,name= 'cart_remove_product'),
     path("cart_update_customer/",cart_update_customer,name="cart_update_customer")
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('account.urls',namespace="account")),
    path('farmers/',include('farmers.urls',namespace="farmers")),
    path('vendors/',include('vendors.urls',namespace="vendors")),
    path('',include('customers.urls',namespace="customers")),
    path("cart/",include("cart.urls",namespace="cart")),
    path('payments/',include('payment.urls',namespace="payment"))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendors/urls.py
from os import name
from django.urls import path
from .views import (
    index,
    shop_index,
    product_detailed,
    all_products,
    checkout,
    order_placed,
    featured_products,
    category_detailed_product,
    all_products,
    product_view,
    add_product,
    resell_product,
    resell_all_products,
    vendors_products

)
app_name = "vendors"
urlpatterns = [
    path("all_p/",all_products,name="all_products"),
    path('',index,name="index"),
    path('vendor/shop_index/',shop_index,name="vendor_shop_index"),
    path('product_detailed/<id>/',product_detailed,name="product_detailed"),
    path('all_products/',all_products,name="all_products"),
    path('vender/checkout/',checkout,name="checkout"),
    path('order_placed_success/',order_placed,name="order_placed"),
    path("featured_products/",featured_products,name="featured_products"),
    path("category_detailed_product/<id>/",category_detailed_product,name="category_detailed_product"),
    path("vendor_product_view/<id>/",product_view,name="product_view"),
    path("resell_product/<id>",add_product,name="add_product"),
    path("resell_products",resell_product,name="resell_product"),
    path("resell_all/",resell_all_products,name="resell_all_products"),
    path("vendors/vendors_products",vendors_products,name="vendors_products")
    
]

vendors/models.py
from django.db import models
from account.models import User
import random
import os
from django.db.models import Q, base
from datetime import datetime
from django.utils.timezone import now
from django.db.models.signals import pre_save
from django.shortcuts import reverse
from products.models import Products
from config.utils import unique_slug_generator,category_unique_slug_generator
# Create your models here.

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "products/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )

def upload_image_path2(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "categories/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )


class ResellProduct(models.Model):
    product =  models.ForeignKey(Products,on_delete=models.CASCADE)
    user =  models.ForeignKey(User,on_delete=models.CASCADE)
    product_price = models.CharField(max_length=255)
    product_image = models.ImageField(upload_to=upload_image_path,null=True,blank=False)
    Active = models.BooleanField(default=True)
    featured_product = models.BooleanField(default=False)

    def __str__(self):
        return str(self.product)


    def customer_absolute_url(self):
        return reverse("customers:product_detailed", kwargs={
            'id': self.id
        })

vendors/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from account.models import User
from cart.models import Cart, CartQuantity
from django.contrib import messages
from django.db.models import Sum
from payment.models import PaidCustomer
from products.models import (
    Category,
    ProductQuerySet,
    Products
)
from .models import (
    ResellProduct
)

# Create your views here.
@login_required(login_url='account:sign_in') 
def index(request):

    user_obj =  User.objects.get(id =  request.user.id)
    paid_c =  PaidCustomer.objects.filter().count()
    product_c = ResellProduct.objects.filter(user =  user_obj).count()
    processing = PaidCustomer.objects.filter(processed =  True)
    system_c = Products.objects.all().count()
    all_orders = PaidCustomer.objects.filter(paid = True)



    context = {
        "paid_c": paid_c,
        "product_c" : product_c  ,
        "processing" : processing,
        "system_c" : system_c,
        "all_orders":all_orders
    }
    
    return render(request,'vendor_index.html',context)


@login_required(login_url='account:sign_in') 
def vendors_products(request):
    all_orders = PaidCustomer.objects.filter(paid = True)

    context = {
         "all_orders":all_orders

    }
    return render(request,'orders_vendor.html',context)

@login_required(login_url='account:sign_in') 
def shop_index(request):
    all_products =  Products.objects.all()
    all_categories = Category.objects.all()
    cart_items = request.session.get("cart_items")
    cart_id =  request.session.get("cart_id")
    if cart_id:
        cart_obj =  Cart.objects.get(id = cart_id if cart_id is not None  else 0)
        cart_quantyty_obj  =  CartQuantity.objects.filter(cart = cart_obj)
        featured_products = Products.objects.filter(featured_product = True)
        total_cart = CartQuantity.objects.filter(cart = cart_obj).aggregate(Sum('total'))

        context = {
            'products':all_products,
            'all_categoris':all_categories,
            'featured_products' : featured_products,
            'cart_items' : cart_items,
            'cart_quantity' : cart_quantyty_obj,
            'total': total_cart['total__sum']
        }
        return render(request,'./shop/shop_index.html',context)

    else:
       
        featured_products = Products.objects.filter(featured_product = True)
        context = {
            'products':all_products,
            'all_categoris':all_categories,
            'featured_products' : featured_products,
            'cart_items' : cart_items,
            
        }
        return render(request,'./shop/shop_index.html',context)




@login_required(login_url='account:sign_in')
def product_detailed(request,id):
    cart_items = request.session.get("cart_items")
    single_product = Products.objects.get(id =  id)
    all_categories = Category.objects.all()
    user_obj = User.objects.get(id =  single_product.user.id)
    more_like_this = Products.objects.filter(user = user_obj)
    featured_products = Products.objects.filter(featured_product = True)
    context = {
        'single_product':single_product,
        'more_like_this': more_like_this,
        'featured_products':featured_products,
        'all_categoris':all_categories,
         'cart_items' : cart_items
    }
    return render(request,'./shop/shop_detailed.html',context)



@login_required(login_url='account:sign_in')
def all_products(request):
    cart_items = request.session.get("cart_items")
    all_categories = Category.objects.all()
    all_products = Products.objects.all()
    name = "All Products"

    context = {
        'all_categoris':all_categories,
        'all_products':all_products,
        'name':name,
        'cart_items' : cart_items
    }
    return render(request,'./shop/all_products.html',context)


@login_required(login_url='account:sign_in')
def checkout(request):
    cart_items = request.session.get("cart_items")
    cart_id =  request.session.get("cart_id")
    cart_obj =  Cart.objects.get(id = int(cart_id))
    cart_quantyty_obj  =  CartQuantity.objects.filter(cart = cart_obj)
    total_cart = CartQuantity.objects.filter(cart = cart_obj).aggregate(Sum('total'))
    all_categories = Category.objects.all()

    context = {
        'total': total_cart['total__sum'],
        'cart_items' : cart_items,
        'cart_quantity' : cart_quantyty_obj,
        'all_categoris':all_categories,


    }

    return render(request,'./shop/checkout.html',context)



@login_required(login_url='account:sign_in')
def order_placed(request):
    cart_items = request.session.get("cart_items")
    cart_id =  request.session.get("cart_id")
    cart_obj =  Cart.objects.get(id = int(cart_id) if cart_id is not None  else 0)
    cart_quantyty_obj  =  CartQuantity.objects.filter(cart = cart_obj)
    total_cart = CartQuantity.objects.filter(cart = cart_obj).aggregate(Sum('total'))
    all_categories = Category.objects.all()
    del request.session['cart_items']
    del request.session['cart_id']
    del request.session['checkout_id']
    del request.session['merchant_id']
    del request.session['phone_no']

    context = {
        'total': total_cart['total__sum'],
        'cart_items' : cart_items,
        'cart_quantity' : cart_quantyty_obj,
        'all_categoris':all_categories,


    }
    return render(request,'./shop/order_placed.html',context)



@login_required(login_url='account:sign_in')
def featured_products(request):
    cart_items = request.session.get("cart_items")
    all_categories = Category.objects.all()
    all_products = Products.objects.filter(featured_product =  True)
    name = "Featured Products"

    context = {
        'all_categoris':all_categories,
        'all_products':all_products,
        'name':name,
        'cart_items' : cart_items
    }
    return render(request,'./shop/all_products.html',context)



@login_required(login_url='account:sign_in')
def category_detailed_product(request,id):
    one_cat =  Category.objects.get(id =  int(id))
    cart_items = request.session.get("cart_items")
    all_categories = Category.objects.all()
    all_products = Products.objects.filter(product_category =  one_cat)
    name = f"Category : {one_cat.category_name}"

    context = {
        'all_categoris':all_categories,
        'all_products':all_products,
        'name':name,
        'cart_items' : cart_items
    }
    return render(request,'./shop/all_products.html',context)



@login_required(login_url='account:sign_in') 
def all_products(request):
  
    cart_items = request.session.get("cart_items")
    all_categories = Category.objects.all()
    all_products = Products.objects.all()
    name = "All Products"

    context = {
        'all_categoris':all_categories,
        'all_products':all_products,
        'name':name,
        'cart_items' : cart_items
    }
    return render(request,'./shop/all_products.html',context)


@login_required(login_url='account:sign_in')
def product_view(request,id):
    product = Products.objects.get(id = id)
    context = {
        'product':product
    }
    return render(request,'vendor_product_view.html',context)

@login_required(login_url='account:sign_in')
def add_product(request,id):
    product = Products.objects.get(id =  id)
    context = {
        "product":product
    }
    return render(request,'vendor_add_product.html',context)


@login_required(login_url='account:sign_in')
def resell_product(request):
    user_id =  request.user.id
    user_obj =  User.objects.get(id =  user_id)
    if request.method == "POST":
        prod_id =  request.POST.get("product_id")
        product_obj =  Products.objects.get(id = int(prod_id))
        product_price =  request.POST.get("product_price")
        status =  request.POST.get("status")
        image =  request.FILES['image']
        featured = request.POST.get("featured")
       
        ResellProduct.objects.create(
            user = user_obj,
            product = product_obj,
            product_price = product_price,
            product_image = image,
            Active =  True if status == 'Active' else False,
            featured_product = True if featured == "Yes" else False
        )
        messages.success(request, 'Product saved successfully.')
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

        print(request.POST)
    
    return render(request,'vendor_add_product.html')



@login_required(login_url='account:sign_in') 
def resell_all_products(request):
    
    user_obj =  User.objects.get(id =  request.user.id)
    all_products =  ResellProduct.objects.filter(user =  user_obj)
    context = {
        'all_products':all_products
    }
    return render(request,'vendor_resell_all_products.html',context)

vendors/templates/vendor_index/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description-gambolthemes" content="">
    <meta name="author-gambolthemes" content="">
    <title>Gambo Supermarket Admin</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/admin-style.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
 </head>

vendors/templates/vendor_index/js.html
{% load static %}
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/chart/highcharts.js' %}"></script>
<script src="{% static 'vendor/chart/exporting.js' %}"></script>
<script src="{% static 'vendor/chart/export-data.js' %}"></script>
<script src="{% static 'vendor/chart/accessibility.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/chart.js' %}"></script>

vendors/templates/vendor_index/nav.html
{% load static %}
<nav class="sb-topnav navbar navbar-expand navbar-light bg-clr">
    <a class="navbar-brand logo-brand" href="index.html">Gambo Supermarket</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
    <a href="{% url 'vendors:vendor_shop_index' %}" class="frnt-link"><i class="fas fa-external-link-alt"></i>Shop</a>
    <ul class="navbar-nav ml-auto mr-md-0">
       <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
  
             <a class="dropdown-item admin-dropdown-item" href="{% url 'account:sign_in' %}">Logout</a>
          </div>
       </li>
    </ul>
 </nav>

vendors/templates/vendor_index/sidebar.html
{% load static %}
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
       <div class="sb-sidenav-menu">
          <div class="nav">
             <a class="nav-link active" href="{% url 'vendors:index' %}">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Dashboard
             </a>
            
             
          
             <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProducts" aria-expanded="false" aria-controls="collapseProducts">
                <div class="sb-nav-link-icon"><i class="fas fa-box"></i></div>
                Products
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
             </a>
             <div class="collapse" id="collapseProducts" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                   <a class="nav-link sub_nav_link" href="{% url 'vendors:all_products' %}">All Products</a>
                   <a class="nav-link sub_nav_link" href="{% url 'vendors:resell_all_products' %}">All Resell Products</a>
         
                </nav>
             </div>
             <a class="nav-link" href="{% url 'vendors:vendors_products' %}">
                <div class="sb-nav-link-icon"><i class="fas fa-cart-arrow-down"></i></div>
                Orders
             </a>
                       
           
           
          </div>
       </div>
    </nav>
 </div>