account/urls.py
from django.urls import path
from .views import index,signup,logout_user,profile_image,activate_account


app_name = "account"

urlpatterns = [
    path('', index,name="sign_in"),
    path('signup/', signup,name="sign_up"),
    path('logout',logout_user,name="logout"),
    path('profile_image/',profile_image,name="upload_image"),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate_account, name='activate')
]

cart/urls.py
from django.urls import path 
from .views import (
    cart_home,
    checkout_home,
    cart_update,
    cart_remove,
    cart_update_customer
)


app_name = 'cart'

urlpatterns = [
    path('',cart_home,name= 'cart_home'),
     path('checkout',checkout_home,name= 'checkout'),
     path('update',cart_update,name= 'cart_update'),
     path('remove',cart_remove,name= 'cart_remove_product'),
     path("cart_update_customer/",cart_update_customer,name="cart_update_customer")
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('account.urls',namespace="account")),
    path('farmers/',include('farmers.urls',namespace="farmers")),
    path('vendors/',include('vendors.urls',namespace="vendors")),
    path('',include('customers.urls',namespace="customers")),
    path("cart/",include("cart.urls",namespace="cart")),
    path('payments/',include('payment.urls',namespace="payment"))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path
from .views import (
    index,
    product_detailed,
    checkout,
    order_placed

)
app_name = "customers"
urlpatterns = [
    path('',index,name="index"),
    path("product_detailed/<id>",product_detailed,name="product_detailed"),
     path('checkout/',checkout,name="checkout"),
     path('order_placed_success/',order_placed,name="order_placed"),
    
]

farmers/urls.py
from django.urls import path
from .views import (
    index,
    all_categories,
    add_category,
    all_products,
    add_product,
    product_view,
    edit_category,
    edit_cat,
    delete_category,
    farmer_products

)


app_name = "farmers"
urlpatterns = [
    path('',index,name="index"),
    path('all_categories/',all_categories,name="all_categories"),
    path('add_category/',add_category,name="add_category"),
    path('all_products/',all_products,name="all_products"),
    path('add_product/',add_product,name="add_product"),
    path('product_view/<id>/',product_view,name="product_view"),
    path('edit_cat/<id>/',edit_category,name="edit_category"),
    path('edit_category/',edit_cat,name="edit_cat"),
    path("delete_product/<id>/",delete_category,name="delete_category"),
    path("farmer_orders/",farmer_products,name="farmer_products")
]

vendors/urls.py
from os import name
from django.urls import path
from .views import (
    index,
    shop_index,
    product_detailed,
    all_products,
    checkout,
    order_placed,
    featured_products,
    category_detailed_product,
    all_products,
    product_view,
    add_product,
    resell_product,
    resell_all_products,
    vendors_products

)
app_name = "vendors"
urlpatterns = [
    path("all_p/",all_products,name="all_products"),
    path('',index,name="index"),
    path('vendor/shop_index/',shop_index,name="vendor_shop_index"),
    path('product_detailed/<id>/',product_detailed,name="product_detailed"),
    path('all_products/',all_products,name="all_products"),
    path('vender/checkout/',checkout,name="checkout"),
    path('order_placed_success/',order_placed,name="order_placed"),
    path("featured_products/",featured_products,name="featured_products"),
    path("category_detailed_product/<id>/",category_detailed_product,name="category_detailed_product"),
    path("vendor_product_view/<id>/",product_view,name="product_view"),
    path("resell_product/<id>",add_product,name="add_product"),
    path("resell_products",resell_product,name="resell_product"),
    path("resell_all/",resell_all_products,name="resell_all_products"),
    path("vendors/vendors_products",vendors_products,name="vendors_products")
    
]

customers/models.py
from django.db import models

# Create your models here.

customers/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from account.models import User
from cart.models import Cart, CartQuantity
from cart.models import CartCustomer,CartQuantityCustomer
from django.contrib import messages
from django.db.models import Sum
from products.models import (
    Category,
    ProductQuerySet,
    Products
)

from vendors.models import ResellProduct

# Create your views here.
def index(request):
    all_products =  ResellProduct.objects.all()
    print(all_products)
    all_categories = Category.objects.all()
    cart_items = request.session.get("cart_items")
    cart_id =  request.session.get("cart_id")
    if cart_id:
        cart_obj =  CartCustomer.objects.get(id = cart_id if cart_id is not None  else 0)
        cart_quantyty_obj  =  CartQuantityCustomer.objects.filter(cart = cart_obj)
        featured_products = ResellProduct.objects.filter(featured_product = True)
        total_cart = CartQuantityCustomer.objects.filter(cart = cart_obj).aggregate(Sum('total'))

        context = {
            'products':all_products,
            'all_categoris':all_categories,
            'featured_products' : featured_products,
            'cart_items' : cart_items,
            'cart_quantity' : cart_quantyty_obj,
            'total': total_cart['total__sum']
        }
        return render(request,'./customer_shop/customer_shop_index.html',context)

    else:
       
        featured_products = ResellProduct.objects.filter(featured_product = True)
        context = {
            'products':all_products,
            'all_categoris':all_categories,
            'featured_products' : featured_products,
            'cart_items' : cart_items,
            
        }
        return render(request,'./customer_shop/customer_shop_index.html',context)




def product_detailed(request,id):
    cart_items = request.session.get("cart_items")
    single_product = ResellProduct.objects.get(id =  id)
    all_categories = Category.objects.all()
    user_obj = User.objects.get(id =  single_product.user.id)
    more_like_this = ResellProduct.objects.filter(user = user_obj)
    featured_products = ResellProduct.objects.filter(featured_product = True)
    context = {
        'single_product':single_product,
        'more_like_this': more_like_this,
        'featured_products':featured_products,
        'all_categoris':all_categories,
         'cart_items' : cart_items
    }
    return render(request,'./customer_shop/shop_detailed.html',context)






@login_required(login_url='account:sign_in')
def checkout(request):
    cart_items = request.session.get("cart_items")
    cart_id =  request.session.get("cart_id")
    cart_obj =  CartCustomer.objects.get(id = int(cart_id))
    cart_quantyty_obj  =  CartQuantityCustomer.objects.filter(cart = cart_obj)
    total_cart = CartQuantityCustomer.objects.filter(cart = cart_obj).aggregate(Sum('total'))
    all_categories = Category.objects.all()

    context = {
        'total': total_cart['total__sum'],
        'cart_items' : cart_items,
        'cart_quantity' : cart_quantyty_obj,
        'all_categoris':all_categories,


    }

    return render(request,'./customer_shop/checkout.html',context)



@login_required(login_url='account:sign_in')
def order_placed(request):
    cart_items = request.session.get("cart_items")
    cart_id =  request.session.get("cart_id")
    cart_obj =  CartCustomer.objects.get(id = int(cart_id) if cart_id is not None  else 0)
    cart_quantyty_obj  =  CartQuantityCustomer.objects.filter(cart = cart_obj)
    total_cart = CartQuantityCustomer.objects.filter(cart = cart_obj).aggregate(Sum('total'))
    all_categories = Category.objects.all()
    del request.session['cart_items']
    del request.session['cart_id']
    del request.session['checkout_id']
    del request.session['merchant_id']
    del request.session['phone_no']

    context = {
        'total': total_cart['total__sum'],
        'cart_items' : cart_items,
        'cart_quantity' : cart_quantyty_obj,
        'all_categoris':all_categories,


    }
    return render(request,'./customer_shop/order_placed.html',context)

customers/templates/customer_shop/index_files/bs_canvas.html
{% load static %}
<div class="bs-canvas bs-canvas-left position-fixed bg-cart h-100">
    <div class="bs-canvas-header side-cart-header p-3 ">
       <div class="d-inline-block  main-cart-title">My Cart <span>( {% if cart_items %}
          {{cart_items}}
          {% else %}
          {{0}}
         {% endif %} Items)</span></div>
       <button type="button" class="bs-canvas-close close" aria-label="Close"><i class="uil uil-multiply"></i></button>
    </div>
    <div class="bs-canvas-body">
       
       <div class="side-cart-items">
         {% if cart_quantity %}
         {% for f in cart_quantity %}
          <div class="cart-item">
             <div class="cart-product-img">
                <img src="{{f.product.product_image.url}}" alt="">
                
             </div>
             <div class="cart-text">
                <h4>{{f.product.product_title}}</h4>
              
                <div class="qty-group">
                   <div class="quantity buttons_added">
                      Ksh {{f.product.product_price}} X {{f.quantity}}
                     
                   </div>
                   <div class="cart-item-price">Ksh {{f.total}}</div>
                </div>
                <button type="button" class="cart-close-btn"><i class="uil uil-multiply"></i></button>
             </div>
          </div>
          {% endfor %}
          {% endif %}
          
       </div>
    </div>
    <div class="bs-canvas-footer">
     
       <div class="main-total-cart">
          <h2>Total</h2>
          <span>Ksh {{total}}</span>
       </div>
       <div class="checkout-cart">
          <a href="#" class="promo-code"></a>
          <a href="{% url 'customers:checkout' %}" class="cart-checkout-btn hover-btn">Proceed to Checkout</a>
       </div>
    </div>
 </div>

customers/templates/customer_shop/index_files/category_model.html
{% load static %}
<div id="category_model" class="header-cate-model main-gambo-model modal fade" tabindex="-1" role="dialog" aria-modal="false">
    <div class="modal-dialog category-area" role="document">
       <div class="category-area-inner">
          <div class="modal-header">
             <button type="button" class="close btn-close" data-dismiss="modal" aria-label="Close">
             <i class="uil uil-multiply"></i>
             </button>
          </div>
          <div class="category-model-content modal-content">
             <div class="cate-header">
                <h4>Select Category</h4>
             </div>
             <ul class="category-by-cat">
                 {% if all_categoris %}
                 {% for all in all_categoris  %}
                <li>
                   <a href="{{all.vendor_category_detailed}}" class="single-cat-item">
                      <div class="icon">
                         <img src="{{all.category_image.url}}" alt="">
                      </div>
                      <div class="text">{{all.category_name}}</div>
                   </a>
                </li>
                {% endfor %}
                {% endif %}
               
             </ul>
            
          </div>
       </div>
    </div>
 </div>

customers/templates/customer_shop/index_files/footer.html
{% load static %}
<footer class="footer">
    <div class="footer-first-row">
       <div class="container">
          <div class="row">
             <div class="col-md-6 col-sm-6">
                <ul class="call-email-alt">
                   <li><a href="#" class="callemail"><i class="uil uil-dialpad-alt"></i>1800-000-000</a></li>
                   <li><a href="#" class="callemail"><i class="uil uil-envelope-alt"></i><span class="__cf_email__" data-cfemail="c8a1a6aea788afa9a5aaa7bbbdb8adbaa5a9baa3adbce6aba7a5">[email&#160;protected]</span></a></li>
                </ul>
             </div>
             <div class="col-md-6 col-sm-6">
                <div class="social-links-footer">
                   <ul>
                      <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                      <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                      <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                      <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                      <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                   </ul>
                </div>
             </div>
          </div>
       </div>
    </div>
    <div class="footer-second-row">
       <div class="container">
          <div class="row">
             <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="second-row-item">
                   <h4>Categories</h4>
                   <ul>
                      <li><a href="#">Fruits and Vegetables</a></li>
                      <li><a href="#">Grocery & Staples</a></li>
                      <li><a href="#">Dairy & Eggs</a></li>
                      <li><a href="#">Beverages</a></li>
                      <li><a href="#">Snacks</a></li>
                      <li><a href="#">Home Care</a></li>
                      <li><a href="#">Noodles & Sauces</a></li>
                      <li><a href="#">Personal Care</a></li>
                      <li><a href="#">Pet Care</a></li>
                      <li><a href="#">Meat & Seafood</a></li>
                      <li><a href="#">Electronics</a></li>
                   </ul>
                </div>
             </div>
             <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="second-row-item">
                   <h4>Useful Links</h4>
                   <ul>
                      <li><a href="about_us.html">About US</a></li>
                      <li><a href="shop_grid.html">Featured Products</a></li>
                      <li><a href="offers.html">Offers</a></li>
                      <li><a href="our_blog.html">Blog</a></li>
                      <li><a href="faq.html">Faq</a></li>
                      <li><a href="career.html">Careers</a></li>
                      <li><a href="contact_us.html">Contact Us</a></li>
                   </ul>
                </div>
             </div>
             <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="second-row-item">
                   <h4>Top Cities</h4>
                   <ul>
                      <li><a href="#">Gurugram</a></li>
                      <li><a href="#">New Delhi</a></li>
                      <li><a href="#">Bangaluru</a></li>
                      <li><a href="#">Mumbai</a></li>
                      <li><a href="#">Hyderabad</a></li>
                      <li><a href="#">Kolkata</a></li>
                      <li><a href="#">Ludhiana</a></li>
                      <li><a href="#">Chandigrah</a></li>
                   </ul>
                </div>
             </div>
             <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="second-row-item-app">
                   <h4>Download App</h4>
                   <ul>
                      <li><a href="#"><img class="download-btn" src="{% static 'frontend/images/download-1.svg' %}" alt=""></a></li>
                      <li><a href="#"><img class="download-btn" src="{% static 'frontend/images/download-2.svg' %}" alt=""></a></li>
                   </ul>
                </div>
                <div class="second-row-item-payment">
                   <h4>Payment Method</h4>
                   <div class="footer-payments">
                      <ul id="paypal-gateway" class="financial-institutes">
                         <li class="financial-institutes__logo">
                            <img alt="Visa" title="Visa" src="{% static 'frontend/images/footer-icons/pyicon-6.svg' %}">
                         </li>
                         <li class="financial-institutes__logo">
                            <img alt="Visa" title="Visa" src="{% static 'frontend/images/footer-icons/pyicon-1.svg' %}">
                         </li>
                         <li class="financial-institutes__logo">
                            <img alt="MasterCard" title="MasterCard" src="{% static 'frontend/images/footer-icons/pyicon-2.svg' %}">
                         </li>
                         <li class="financial-institutes__logo">
                            <img alt="American Express" title="American Express" src="{% static 'frontend/images/footer-icons/pyicon-3.svg' %}">
                         </li>
                         <li class="financial-institutes__logo">
                            <img alt="Discover" title="Discover" src="{% static 'frontend/images/footer-icons/pyicon-4.svg' %}">
                         </li>
                      </ul>
                   </div>
                </div>
                <div class="second-row-item-payment">
                   <h4>Newsletter</h4>
                   <div class="newsletter-input">
                      <input id="email" name="email" type="text" placeholder="Email Address" class="form-control input-md" required="">
                      <button class="newsletter-btn hover-btn" type="submit"><i class="uil uil-telegram-alt"></i></button>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>
    <div class="footer-last-row">
       <div class="container">
          <div class="row">
             <div class="col-md-12">
                <div class="footer-bottom-links">
                   <ul>
                      <li><a href="about_us.html">About</a></li>
                      <li><a href="contact_us.html">Contact</a></li>
                      <li><a href="privacy_policy.html">Privacy Policy</a></li>
                      <li><a href="term_and_conditions.html">Term & Conditions</a></li>
                      <li><a href="refund_and_return_policy.html">Refund & Return Policy</a></li>
                   </ul>
                </div>
                <div class="copyright-text">
                   <i class="uil uil-copyright"></i>Copyright 2020 <b>Gambolthemes</b> . All rights reserved
                </div>
             </div>
          </div>
       </div>
    </div>
 </footer>

customers/templates/customer_shop/index_files/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=9">
    <meta name="description" content="Gambolthemes">
    <meta name="author" content="Gambolthemes">
    <title>Gambo - Index</title>
    <link rel="icon" type="image/png" href="images/fav.png">
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href='{% static 'frontend/vendor/unicons-2.0.1/css/unicons.css' %}' rel='stylesheet'>
    <link href="{% static 'frontend/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/css/night-mode.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/vendor/OwlCarousel/assets/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/vendor/OwlCarousel/assets/owl.theme.default.min.css' %}" rel="stylesheet">
    <link href="{% static 'frontend/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'frontend/vendor/semantic/semantic.min.css' %}">
 </head>

customers/templates/customer_shop/index_files/header.html
{% load static %}
<header class="header clearfix">
    <div class="top-header-group">
       <div class="top-header">
          <div class="res_main_logo">
             <a href="index.html"><img src="images/dark-logo-1.svg" alt=""></a>
          </div>
          <div class="main_logo" id="logo">
             <a href="index.html"><img src="{% static 'images/logo.svg' %}" alt=""></a>
             <a href="index.html"><img class="logo-inverse" src="{% static 'images/dark-logo.svg' %}" alt=""></a>
          </div>
          
          <div class="search120">
             <div class="ui search">
                <div class="ui left icon input swdh10">
                   <input class="prompt srch10" type="text" placeholder="Search for products..">
                   <i class='uil uil-search-alt icon icon1'></i>
                </div>
             </div>
          </div>
          <div class="header_right">
             <ul>
                <li>
                   <a href="#" class="offer-link"><i class="uil uil-phone-alt"></i>1800-000-000</a>
                </li>
             
               
              
                <li class="ui dropdown">
                   <a href="#" class="opts_account">
                   <img src="{% static 'frontend/images/avatar/img-5.jpg' %}" alt="">
                   <span class="user__name">{{request.user.username}}</span>
                   <i class="uil uil-angle-down"></i>
                   </a>
                   <div class="menu dropdown_account">
                      <div class="night_mode_switch__btn">
                         <a href="#" id="night-mode" class="btn-night-mode">
                         <i class="uil uil-moon"></i> Night mode
                         <span class="btn-night-mode-switch">
                         <span class="uk-switch-button"></span>
                         </span>
                         </a>
                      </div>
                      
                      <a href="{% url 'account:logout' %}" class="item channel_item"><i class="uil uil-lock-alt icon__1"></i>Logout</a>
                   </div>
                </li>
             </ul>
          </div>
       </div>
    </div>
    <div class="sub-header-group">
       <div class="sub-header">
          <div class="ui dropdown">
             <a href="#" class="category_drop hover-btn" data-toggle="modal" data-target="#category_model" title="Categories"><i class="uil uil-apps"></i><span class="cate__icon">Select Category</span></a>
          </div>
          <nav class="navbar navbar-expand-lg navbar-light py-3">
             <div class="container-fluid">
                <button class="navbar-toggler menu_toggle_btn" type="button" data-target="#navbarSupportedContent"><i class="uil uil-bars"></i></button>
                <div class="collapse navbar-collapse d-flex flex-column flex-lg-row flex-xl-row justify-content-lg-end bg-dark1 p-3 p-lg-0 mt1-5 mt-lg-0 mobileMenu" id="navbarSupportedContent">
                   <ul class="navbar-nav main_nav align-self-stretch">
                      <li class="nav-item"><a href="/" class="nav-link active" title="Home">Home</a></li>
                      <li class="nav-item"><a href="{% url 'vendors:all_products' %}" class="nav-link new_item" title="New Products">All Products</a></li>
                      <li class="nav-item"><a href="{% url 'vendors:featured_products' %}" class="nav-link" title="Featured Products">Featured Products</a></li>
                     
                   
                   </ul>
                </div>
             </div>
          </nav>
          <div class="catey__icon">
             <a href="#" class="cate__btn" data-toggle="modal" data-target="#category_model" title="Categories"><i class="uil uil-apps"></i></a>
          </div>
          <div class="header_cart order-1">
             <a href="#" class="cart__btn hover-btn pull-bs-canvas-left" title="Cart"><i class="uil uil-shopping-cart-alt"></i><span>Cart</span><ins>
                {% if cart_items %}
                
                {{cart_items}}

                {% else %}

                {{0}}

                {% endif %}
             </ins><i class="uil uil-angle-down"></i></a>
          </div>
          <div class="search__icon order-1">
             <a href="#" class="search__btn hover-btn" data-toggle="modal" data-target="#search_model" title="Search"><i class="uil uil-search"></i></a>
          </div>
       </div>
    </div>
 </header>

customers/templates/customer_shop/index_files/js.html
{% load static %}
<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script><script src="{% static 'frontend/js/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'frontend/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'frontend/vendor/OwlCarousel/owl.carousel.js' %}"></script>
      <script src="{% static 'frontend/vendor/semantic/semantic.min.js' %}"></script>
      <script src="{% static 'frontend/js/jquery.countdown.min.js' %}"></script>
      <script src="{% static 'frontend/js/custom.js' %}"></script>
      <script src="{% static 'frontend/js/offset_overlay.js' %}"></script>
      <script src="{% static 'frontend/js/night-mode.js' %}"></script>

customers/templates/customer_shop/index_files/search_model.html
{% load static %}
<div id="search_model" class="header-cate-model main-gambo-model modal fade" tabindex="-1" role="dialog" aria-modal="false">
    <div class="modal-dialog search-ground-area" role="document">
       <div class="category-area-inner">
          <div class="modal-header">
             <button type="button" class="close btn-close" data-dismiss="modal" aria-label="Close">
             <i class="uil uil-multiply"></i>
             </button>
          </div>
          <div class="category-model-content modal-content">
             <div class="search-header">
                <form action="#">
                   <input type="search" placeholder="Search for products...">
                   <button type="submit"><i class="uil uil-search"></i></button>
                </form>
             </div>
             <div class="search-by-cat">
                <a href="#" class="single-cat">
                   <div class="icon">
                      <img src="images/category/icon-1.svg" alt="">
                   </div>
                   <div class="text">
                      Fruits and Vegetables
                   </div>
                </a>
                <a href="#" class="single-cat">
                   <div class="icon">
                      <img src="images/category/icon-2.svg" alt="">
                   </div>
                   <div class="text"> Grocery & Staples </div>
                </a>
                <a href="#" class="single-cat">
                   <div class="icon">
                      <img src="images/category/icon-3.svg" alt="">
                   </div>
                   <div class="text"> Dairy & Eggs </div>
                </a>
                <a href="#" class="single-cat">
                   <div class="icon">
                      <img src="images/category/icon-4.svg" alt="">
                   </div>
                   <div class="text"> Beverages </div>
                </a>
                <a href="#" class="single-cat">
                   <div class="icon">
                      <img src="images/category/icon-5.svg" alt="">
                   </div>
                   <div class="text"> Snacks </div>
                </a>
                <a href="#" class="single-cat">
                   <div class="icon">
                      <img src="images/category/icon-6.svg" alt="">
                   </div>
                   <div class="text"> Home Care </div>
                </a>
                <a href="#" class="single-cat">
                   <div class="icon">
                      <img src="images/category/icon-7.svg" alt="">
                   </div>
                   <div class="text"> Noodles & Sauces </div>
                </a>
                <a href="#" class="single-cat">
                   <div class="icon">
                      <img src="images/category/icon-8.svg" alt="">
                   </div>
                   <div class="text"> Personal Care </div>
                </a>
                <a href="#" class="single-cat">
                   <div class="icon">
                      <img src="images/category/icon-9.svg" alt="">
                   </div>
                   <div class="text"> Pet Care </div>
                </a>
             </div>
          </div>
       </div>
    </div>
 </div>