cart/urls.py
from django.urls import path 
from .views import (
    cart_home,
    checkout_home,
    cart_update,
    cart_remove,
    cart_update_customer
)


app_name = 'cart'

urlpatterns = [
    path('',cart_home,name= 'cart_home'),
     path('checkout',checkout_home,name= 'checkout'),
     path('update',cart_update,name= 'cart_update'),
     path('remove',cart_remove,name= 'cart_remove_product'),
     path("cart_update_customer/",cart_update_customer,name="cart_update_customer")
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('account.urls',namespace="account")),
    path('farmers/',include('farmers.urls',namespace="farmers")),
    path('vendors/',include('vendors.urls',namespace="vendors")),
    path('',include('customers.urls',namespace="customers")),
    path("cart/",include("cart.urls",namespace="cart")),
    path('payments/',include('payment.urls',namespace="payment"))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from os import name
from django.urls import path

from .views import (

    lipa_na_mpesa_online,

    mpesa_queyr,
    startmpesaRequest,
    lipa_na_mpesa_online_customer,
    startmpesaRequest_customer,
    mpesa_queyr_customer
   
)

app_name = "mpesa"
urlpatterns = [
 
    path('online/lipa', lipa_na_mpesa_online, name='lipa_na_mpesa'),

    path('mpesa_query/',mpesa_queyr,name="mpesa_qury"),
    path('startMpesaRequest',startmpesaRequest,name="start_mpesa"),
    path("lipa_na_mpesa/customer/",lipa_na_mpesa_online_customer,name="lipa_na_mpesa_online_customer"),
    path("start_mpesa_req/",startmpesaRequest_customer,name="startmpesaRequest_customer"),
    path("mpesa_queyr_customer/",mpesa_queyr_customer,name="mpesa_queyr_customer")
   

]

vendors/urls.py
from os import name
from django.urls import path
from .views import (
    index,
    shop_index,
    product_detailed,
    all_products,
    checkout,
    order_placed,
    featured_products,
    category_detailed_product,
    all_products,
    product_view,
    add_product,
    resell_product,
    resell_all_products,
    vendors_products

)
app_name = "vendors"
urlpatterns = [
    path("all_p/",all_products,name="all_products"),
    path('',index,name="index"),
    path('vendor/shop_index/',shop_index,name="vendor_shop_index"),
    path('product_detailed/<id>/',product_detailed,name="product_detailed"),
    path('all_products/',all_products,name="all_products"),
    path('vender/checkout/',checkout,name="checkout"),
    path('order_placed_success/',order_placed,name="order_placed"),
    path("featured_products/",featured_products,name="featured_products"),
    path("category_detailed_product/<id>/",category_detailed_product,name="category_detailed_product"),
    path("vendor_product_view/<id>/",product_view,name="product_view"),
    path("resell_product/<id>",add_product,name="add_product"),
    path("resell_products",resell_product,name="resell_product"),
    path("resell_all/",resell_all_products,name="resell_all_products"),
    path("vendors/vendors_products",vendors_products,name="vendors_products")
    
]

vendors/models.py
from django.db import models
from account.models import User
import random
import os
from django.db.models import Q, base
from datetime import datetime
from django.utils.timezone import now
from django.db.models.signals import pre_save
from django.shortcuts import reverse
from products.models import Products
from config.utils import unique_slug_generator,category_unique_slug_generator
# Create your models here.

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "products/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )

def upload_image_path2(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "categories/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )


class ResellProduct(models.Model):
    product =  models.ForeignKey(Products,on_delete=models.CASCADE)
    user =  models.ForeignKey(User,on_delete=models.CASCADE)
    product_price = models.CharField(max_length=255)
    product_image = models.ImageField(upload_to=upload_image_path,null=True,blank=False)
    Active = models.BooleanField(default=True)
    featured_product = models.BooleanField(default=False)

    def __str__(self):
        return str(self.product)


    def customer_absolute_url(self):
        return reverse("customers:product_detailed", kwargs={
            'id': self.id
        })

vendors/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from account.models import User
from cart.models import Cart, CartQuantity
from django.contrib import messages
from django.db.models import Sum
from payment.models import PaidCustomer
from products.models import (
    Category,
    ProductQuerySet,
    Products
)
from .models import (
    ResellProduct
)

# Create your views here.
@login_required(login_url='account:sign_in') 
def index(request):

    user_obj =  User.objects.get(id =  request.user.id)
    paid_c =  PaidCustomer.objects.filter().count()
    product_c = ResellProduct.objects.filter(user =  user_obj).count()
    processing = PaidCustomer.objects.filter(processed =  True)
    system_c = Products.objects.all().count()
    all_orders = PaidCustomer.objects.filter(paid = True)



    context = {
        "paid_c": paid_c,
        "product_c" : product_c  ,
        "processing" : processing,
        "system_c" : system_c,
        "all_orders":all_orders
    }
    
    return render(request,'vendor_index.html',context)


@login_required(login_url='account:sign_in') 
def vendors_products(request):
    all_orders = PaidCustomer.objects.filter(paid = True)

    context = {
         "all_orders":all_orders

    }
    return render(request,'orders_vendor.html',context)

@login_required(login_url='account:sign_in') 
def shop_index(request):
    all_products =  Products.objects.all()
    all_categories = Category.objects.all()
    cart_items = request.session.get("cart_items")
    cart_id =  request.session.get("cart_id")
    if cart_id:
        cart_obj =  Cart.objects.get(id = cart_id if cart_id is not None  else 0)
        cart_quantyty_obj  =  CartQuantity.objects.filter(cart = cart_obj)
        featured_products = Products.objects.filter(featured_product = True)
        total_cart = CartQuantity.objects.filter(cart = cart_obj).aggregate(Sum('total'))

        context = {
            'products':all_products,
            'all_categoris':all_categories,
            'featured_products' : featured_products,
            'cart_items' : cart_items,
            'cart_quantity' : cart_quantyty_obj,
            'total': total_cart['total__sum']
        }
        return render(request,'./shop/shop_index.html',context)

    else:
       
        featured_products = Products.objects.filter(featured_product = True)
        context = {
            'products':all_products,
            'all_categoris':all_categories,
            'featured_products' : featured_products,
            'cart_items' : cart_items,
            
        }
        return render(request,'./shop/shop_index.html',context)




@login_required(login_url='account:sign_in')
def product_detailed(request,id):
    cart_items = request.session.get("cart_items")
    single_product = Products.objects.get(id =  id)
    all_categories = Category.objects.all()
    user_obj = User.objects.get(id =  single_product.user.id)
    more_like_this = Products.objects.filter(user = user_obj)
    featured_products = Products.objects.filter(featured_product = True)
    context = {
        'single_product':single_product,
        'more_like_this': more_like_this,
        'featured_products':featured_products,
        'all_categoris':all_categories,
         'cart_items' : cart_items
    }
    return render(request,'./shop/shop_detailed.html',context)



@login_required(login_url='account:sign_in')
def all_products(request):
    cart_items = request.session.get("cart_items")
    all_categories = Category.objects.all()
    all_products = Products.objects.all()
    name = "All Products"

    context = {
        'all_categoris':all_categories,
        'all_products':all_products,
        'name':name,
        'cart_items' : cart_items
    }
    return render(request,'./shop/all_products.html',context)


@login_required(login_url='account:sign_in')
def checkout(request):
    cart_items = request.session.get("cart_items")
    cart_id =  request.session.get("cart_id")
    cart_obj =  Cart.objects.get(id = int(cart_id))
    cart_quantyty_obj  =  CartQuantity.objects.filter(cart = cart_obj)
    total_cart = CartQuantity.objects.filter(cart = cart_obj).aggregate(Sum('total'))
    all_categories = Category.objects.all()

    context = {
        'total': total_cart['total__sum'],
        'cart_items' : cart_items,
        'cart_quantity' : cart_quantyty_obj,
        'all_categoris':all_categories,


    }

    return render(request,'./shop/checkout.html',context)



@login_required(login_url='account:sign_in')
def order_placed(request):
    cart_items = request.session.get("cart_items")
    cart_id =  request.session.get("cart_id")
    cart_obj =  Cart.objects.get(id = int(cart_id) if cart_id is not None  else 0)
    cart_quantyty_obj  =  CartQuantity.objects.filter(cart = cart_obj)
    total_cart = CartQuantity.objects.filter(cart = cart_obj).aggregate(Sum('total'))
    all_categories = Category.objects.all()
    del request.session['cart_items']
    del request.session['cart_id']
    del request.session['checkout_id']
    del request.session['merchant_id']
    del request.session['phone_no']

    context = {
        'total': total_cart['total__sum'],
        'cart_items' : cart_items,
        'cart_quantity' : cart_quantyty_obj,
        'all_categoris':all_categories,


    }
    return render(request,'./shop/order_placed.html',context)



@login_required(login_url='account:sign_in')
def featured_products(request):
    cart_items = request.session.get("cart_items")
    all_categories = Category.objects.all()
    all_products = Products.objects.filter(featured_product =  True)
    name = "Featured Products"

    context = {
        'all_categoris':all_categories,
        'all_products':all_products,
        'name':name,
        'cart_items' : cart_items
    }
    return render(request,'./shop/all_products.html',context)



@login_required(login_url='account:sign_in')
def category_detailed_product(request,id):
    one_cat =  Category.objects.get(id =  int(id))
    cart_items = request.session.get("cart_items")
    all_categories = Category.objects.all()
    all_products = Products.objects.filter(product_category =  one_cat)
    name = f"Category : {one_cat.category_name}"

    context = {
        'all_categoris':all_categories,
        'all_products':all_products,
        'name':name,
        'cart_items' : cart_items
    }
    return render(request,'./shop/all_products.html',context)



@login_required(login_url='account:sign_in') 
def all_products(request):
  
    cart_items = request.session.get("cart_items")
    all_categories = Category.objects.all()
    all_products = Products.objects.all()
    name = "All Products"

    context = {
        'all_categoris':all_categories,
        'all_products':all_products,
        'name':name,
        'cart_items' : cart_items
    }
    return render(request,'./shop/all_products.html',context)


@login_required(login_url='account:sign_in')
def product_view(request,id):
    product = Products.objects.get(id = id)
    context = {
        'product':product
    }
    return render(request,'vendor_product_view.html',context)

@login_required(login_url='account:sign_in')
def add_product(request,id):
    product = Products.objects.get(id =  id)
    context = {
        "product":product
    }
    return render(request,'vendor_add_product.html',context)


@login_required(login_url='account:sign_in')
def resell_product(request):
    user_id =  request.user.id
    user_obj =  User.objects.get(id =  user_id)
    if request.method == "POST":
        prod_id =  request.POST.get("product_id")
        product_obj =  Products.objects.get(id = int(prod_id))
        product_price =  request.POST.get("product_price")
        status =  request.POST.get("status")
        image =  request.FILES['image']
        featured = request.POST.get("featured")
       
        ResellProduct.objects.create(
            user = user_obj,
            product = product_obj,
            product_price = product_price,
            product_image = image,
            Active =  True if status == 'Active' else False,
            featured_product = True if featured == "Yes" else False
        )
        messages.success(request, 'Product saved successfully.')
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

        print(request.POST)
    
    return render(request,'vendor_add_product.html')



@login_required(login_url='account:sign_in') 
def resell_all_products(request):
    
    user_obj =  User.objects.get(id =  request.user.id)
    all_products =  ResellProduct.objects.filter(user =  user_obj)
    context = {
        'all_products':all_products
    }
    return render(request,'vendor_resell_all_products.html',context)

vendors/templates/shop/checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, shrink-to-fit=9">
        <meta name="description" content="Gambolthemes">
        <meta name="author" content="Gambolthemes">
        <title>Gambo - Checkout</title>
        <link rel="icon" type="image/png" href="images/fav.png">
        <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <link href='vendor/unicons-2.0.1/css/unicons.css' rel='stylesheet'>
        <link href="{% static 'frontend/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'frontend/css/responsive.css' %}" rel="stylesheet">
        <link href="{% static 'frontend/css/night-mode.css' %}" rel="stylesheet">
        <link href="{% static 'frontend/css/step-wizard.css' %}" rel="stylesheet">
        <link href="{% static 'frontend/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
        <link href="{% static 'frontend/vendor/OwlCarousel/assets/owl.carousel.css' %}" rel="stylesheet">
        <link href="{% static 'frontend/vendor/OwlCarousel/assets/owl.theme.default.min.css' %}" rel="stylesheet">
        <link href="{% static 'frontend/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'frontend/vendor/semantic/semantic.min.css' %}">
     </head>
   <body>
    {% include './index_files/category_model.html' %}
    {% include './index_files/search_model.html' %}
    {% include './index_files/bs_canvas.html' %}
    {% include './index_files/header.html' %}
      <div class="wrapper">
         <div class="gambo-Breadcrumb">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                           <li class="breadcrumb-item"><a href="{% url 'vendors:vendor_shop_index' %}">Home</a></li>
                           <li class="breadcrumb-item active" aria-current="page">Checkout</li>
                        </ol>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
         <div class="all-product-grid">
            <div class="container">
               <div class="row">
                  <div class="col-lg-8 col-md-7">
                     <div id="checkout_wizard" class="checkout accordion left-chck145">
                        <div class="checkout-step">
                           <div class="checkout-card" id="headingOne">
                              <span class="checkout-step-number">1</span>
                              <h4 class="checkout-step-title">
                                 <button class="wizard-btn" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"> Phone Via Mpesa</button>
                              </h4>
                           </div>
                           <div id="collapseOne" class="collapse in show" data-parent="#checkout_wizard">
                              <div class="checkout-step-body">
                                 <p>We need your safaricom phone number to be able to pay for product.</p>
                                 <p class="phn145">Number format <span>07XXXXXXXXX</span><a class="edit-no-btn hover-btn" data-toggle="collapse" href="#edit-number">Pay</a></p>
                                 <div class="collapse" id="edit-number">
                                    <div class="row">
                                       <div class="col-lg-8">
                                          <div class="checkout-login">
                                             <form method="POST" action="{% url 'mpesa:lipa_na_mpesa' %}">
                                                {% csrf_token %}
                                                <div class="login-phone">
                                                   <input name="phone" type="text" class="form-control" placeholder="Phone Number">
                                                </div>
                                                <button type="submit" class="chck-btn hover-btn"  data-toggle="collapse" >Pay Via Mpesa</button>
                                             </form>
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                                
                              </div>
                           </div>
                        </div>
                      
  
                       
                     </div>
                  </div>
                  <div class="col-lg-4 col-md-5">
                      
                     <div class="pdpt-bg mt-0">
                        <div class="pdpt-title">
                           <h4>Order Summary</h4>
                        </div>
                        {% if cart_quantity  %}
                        {% for f in cart_quantity %}
                        <div class="right-cart-dt-body">
                            <div class="cart-item border_radius">
                               <div class="cart-product-img">
                                  <img src="{{f.product.product_Image_Field.url}}" alt="">
                                
                               </div>
                               <div class="cart-text">
                                  <h4>{{f.product.product_title}}</h4>
                                  <div class="cart-item-price">Ksh {{f.product.product_price}} X {{f.quantity}} = Ksh {{f.total}}</div>
                                  <button type="button" class="cart-close-btn"><i class="uil uil-multiply"></i></button>
                               </div>
                            </div>
                         </div>
                         {% endfor %}
                         {% endif %}
                      
                       
                        <div class="main-total-cart">
                           <h2>Total</h2>
                           <span>Ksh {{total}}</span>
                        </div>
                        <div class="payment-secure">
                           <i class="uil uil-padlock"></i>Secure checkout
                        </div>
                     </div>
                   
                     <div class="checkout-safety-alerts">
                        <p><i class="uil uil-sync"></i>100% Replacement Guarantee</p>
                        <p><i class="uil uil-check-square"></i>100% Genuine Products</p>
                        <p><i class="uil uil-shield-check"></i>Secure Payments</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      {% include './index_files/footer.html' %}
      {% include './index_files/js.html' %}
   </body>
</html>

vendors/templates/shop/order_placed.html
<!DOCTYPE html>
<html lang="en">
   {% include './index_files/head.html' %}
   <body>
      {% include './index_files/category_model.html' %}
      {% include './index_files/search_model.html' %}
      {% include './index_files/bs_canvas.html' %}
      {% include './index_files/header.html' %}
      <div class="wrapper">
         <div class="gambo-Breadcrumb">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                           <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                           <li class="breadcrumb-item active" aria-current="page">Order Placed</li>
                        </ol>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
         <div class="all-product-grid">
            <div class="container">
               <div class="row justify-content-center">
                  <div class="col-lg-6 col-md-8">
                     <div class="order-placed-dt">
                        <i class="uil uil-check-circle icon-circle"></i>
                        <h2>Order Successfully Placed</h2>
                        <p>Thank you for your order!</p>
                     
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      {% include './index_files/footer.html' %}
      {% include './index_files/js.html' %}
   </body>
</html>

vendors/templates/shop/shop_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% include './index_files/head.html' %}
   <body>
      {% include './index_files/category_model.html' %}
      {% include './index_files/search_model.html' %}
      {% include './index_files/bs_canvas.html' %}
      {% include './index_files/header.html' %}
      <div class="wrapper">
         <div class="main-banner-slider">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <div class="owl-carousel offers-banner owl-theme">
                         {% if products %}
                         {% for f in products %}
                        <div class="item">
                           <div class="offer-item">
                              <div class="offer-item-img">
                                 <div class="gambo-overlay"></div>
                                 <img src="{{f.product_Image_Field.url}}" alt="">
                              </div>
                              <div class="offer-text-dt">
                                 <div class="offer-top-text-banner">
                                    
                                    <div class="top-text-1">Buy More & Save More</div>
                                    <span>{{f.product_title}}</span>
                                 </div>
                                 <a href="{{f.vendor_absolute_url}}" class="Offer-shop-btn hover-btn">Shop Now</a>
                              </div>
                           </div>
                        </div>
                        {% endfor %}
                        {% endif %}
                       
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="section145">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <div class="main-title-tt">
                        <div class="main-title-left">
                           <span>Shop By</span>
                           <h2>Categories</h2>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-12">
                     <div class="owl-carousel cate-slider owl-theme">
                         {% if all_categoris %}
                         {% for c in all_categoris  %}
                        <div class="item">
                           <a href="#" class="category-item">
                              <div class="cate-img">
                                 <img src="{{c.category_image.url}}" alt="">
                              </div>
                              <h4>{{c.category_name}}</h4>
                           </a>
                        </div>
                        {% endfor %}
                        {% endif %}
                        
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="section145">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <div class="main-title-tt">
                        <div class="main-title-left">
                           <span>For You</span>
                           <h2>Top Featured Products</h2>
                        </div>
                        <a href="{% url 'vendors:featured_products' %}" class="see-more-btn">See All</a>
                     </div>
                  </div>
                  <div class="col-md-12">
                     <div class="owl-carousel featured-slider owl-theme">
                         {% if featured_products %}
                         {% for fe in featured_products  %}
                        <div class="item">
                           <div class="product-item">
                              <a href="{{fe.vendor_absolute_url}}" class="product-img">
                                 <img src="{{fe.product_Image_Field.url}}" alt="">
                                 <div class="product-absolute-options">
                                    
                                    <span class="like-icon" title="wishlist"></span>
                                 </div>
                              </a>
                              <div class="product-text-dt">
                                 <p>Available<span>(In Stock)</span></p>
                                 <h4>{{fe.product_title}}</h4>
                                 <div class="product-price">Ksh {{fe.product_price}}</div>
                                 <div class="qty-cart">
                                    <div class="quantity buttons_added">
                                       <input type="button" value="-" class="minus minus-btn">
                                       <input type="number" step="1" name="quantity" value="1" class="input-text qty text">
                                       <input type="button" value="+" class="plus plus-btn">
                                    </div>
                                    <span class="cart-icon"><i class="uil uil-shopping-cart-alt"></i></span>
                                 </div>
                              </div>
                           </div>
                        </div>
                        {% endfor %}
                        {% endif %}
                        
                       
                     </div>
                  </div>
               </div>
            </div>
         </div>
         
        
         <div class="section145">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <div class="main-title-tt">
                        <div class="main-title-left">
                           <span>For You</span>
                           <h2>Added New Products</h2>
                        </div>
                        <a href="{% url 'vendors:all_products' %}" class="see-more-btn">See All</a>
                     </div>
                  </div>
                  <div class="col-md-12">
                     <div class="owl-carousel featured-slider owl-theme">
                         {% if products %}
                         {% for p in products  %}
                        <div class="item">
                           <div class="product-item">
                              <a href="{{p.vendor_absolute_url}}" class="product-img">
                                 <img src="{{p.product_Image_Field.url}}" alt="">
                                 <div class="product-absolute-options">
                                    <span class="offer-badge-1">New</span>
                                    <span class="like-icon" title="wishlist"></span>
                                 </div>
                              </a>
                              <div class="product-text-dt">
                                 <p>Available<span>(In Stock)</span></p>
                                 <h4>{{p.product_title}}</h4>
                                 <div class="product-price">Ksh {{p.product_price}}</div>
                                 <div class="qty-cart">
                                    <div class="quantity buttons_added">
                                       <input type="button" value="-" class="minus minus-btn">
                                       <input type="number" step="1" name="quantity" value="1" class="input-text qty text">
                                       <input type="button" value="+" class="plus plus-btn">
                                    </div>
                                    <span class="cart-icon"><i class="uil uil-shopping-cart-alt"></i></span>
                                 </div>
                              </div>
                           </div>
                        </div>
                        {% endfor %}
                        {% endif %}
                       
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      {% include './index_files/footer.html' %}
      {% include './index_files/js.html' %}
   </body>
</html>